services:
  monkeyocr-webapp:
    image: quantatrisk/monkeyocr-webapp:latest
    ports:
      - "${API_PORT:-8001}:8001"
    env_file:
      - .env
    environment:
      # Override specific values for container
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ocr_data:/app/data      # 改为 ocr_data
      - ocr_static:/app/static  # 改为 ocr_static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - api-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory ${REDIS_MAX_MEMORY:-256mb} --maxmemory-policy allkeys-lru
    volumes:
      - ./redis_data:/data
    networks:
      - api-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  ocr_data:
  ocr_static:

networks:
  api-network:
    driver: bridge
