version: '3.8'

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  monkeyocr-webapp:
    build:
      target: backend-build
    ports:
      - "5173:80"    # Development port
      - "8001:8001"  # Direct backend access
    environment:
      - PYTHONPATH=/app
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:3000
      - RELOAD=true
      - DEBUG=true
    volumes:
      # Mount source code for development
      - ./backend:/app:ro
      - ./frontend/dist:/app/static/frontend:ro
      # Persistent data (read/write)
      - ./data:/app/data
      - ./static:/app/static
    command: >
      sh -c "
        echo 'Development mode: Starting backend with auto-reload...' &&
        uvicorn main:app --host 0.0.0.0 --port 8001 --reload &
        BACKEND_PID=$$! &&
        echo 'Waiting for backend...' &&
        sleep 5 &&
        echo 'Starting nginx...' &&
        nginx -g 'daemon off;'
      "
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G